rm -rf \
    boot-files \
    bottom \
    broot \
    busybox \
    chess-tui \
    eza \
    gcc-4.6.1-2 \
    hex \
    linux \
    loc \
    lpm \
    minos-static \
    opt-nodejs-0.8.18-1 \
    python3.2-static-raw.githubusercontent.com \
    py \
    vim \
    xplr \
    gcc-4.6.1-2.tar.xz \
    nate_os.img \
    opt-nodejs-0.8.18-1.tar.xz \
    python3.2-static-raw.githubusercontent.com.tar.xz \
    vim.tar.xz \
