#!/bin/sh
usage() {
    echo "Usage: netconf <interface> <IPv4_address> <gateway>"
    echo -e "\n"

    echo "  This Bash script is designed to configure network"
    echo "  interfaces and set the default gateway on a Linux"
    echo "  system. It accepts three arguments:"
    echo -e "\n"

    echo "    - <interface> : network interface to be configured (e.g., eth0)"
    echo "    - <ipv4_addr> : address to assign to the specified interface"
    echo "    - <gateway>   : IP address of the default gateway"
    echo -e "\n"

    echo "Example: netconf eth0 10.0.2.15 10.0.2.2"
}

if [ "$#" -ne 3 ]; then
    usage
    exit 1
fi

interface=$1
ip_address=$2
gateway=$3

echo "Configuring $interface with IP address $ip_address and netmask 255.255.255.0"
ifconfig "$interface" up
udhcpc -i "$interface"
ifconfig "$interface" "$ip_address" netmask 255.255.255.0

echo "Setting default gateway to $gateway"
route add default gw "$gateway"

echo "Network configuration completed successfully"

